pypi-transformers: Autospec creation for update from version 4.50.3 to version 4.51.0
ARAVINDHAN T (1):
      Updated model card for Qwen2  (#37192)

AbdelKarim ELJANDOUBI (1):
      fix Gemma3 Config (#36893)

Abhishek Ranjan (1):
      chore: Update model doc for code_llama (#37115)

Abu Bakr Soliman (1):
      Support QuestionAnswering Module for ModernBert based models. (#35566)

Afanti (2):
      fix typos in the tests directory (#36932)
      fix typos in the code comments and error messages (#36993)

Aritra Roy Gosthipaty (1):
      Update installation.md (#36826)

Armaghan Shakir (1):
      Create and Expose SamVisionModel as public for better accessibility (#36493)

Arthur (1):
      Add llama4 (#37307)

Arthur Zucker (1):
      push v4.51.0.dev0

Avigyan Sinha (1):
      feat: updated model card for qwen_2.5_vl (#37099)

Bimal Gajera (1):
      Update model card for Cohere (#37056)

Bo Zheng (1):
      Adding Qwen3 and Qwen3MoE (#36878)

Bowen Bao (1):
      [doc] Fix link for Quark quantization page (#37179)

Chathumina Vimukthi (1):
      Updated model card for distilbert (#37157)

Cyril Vallez (11):
      Simplify keep_in_fp32_modules logic (#36722)
      Add Phi4 multimodal (#36939)
      Allow easy registration of custom attention functions (#36889)
      Fix state_dict map location when quantized (#37086)
      Fix AttentionInterface following feedback (#37010)
      Remove low_cpu_mem_usage and _fast_init (#36963)
      Fix meta state dict loading with quantizers (#37136)
      Revert #37031 (#37178)
      Fix test (#37213)
      Fix deepspeed loading (#37281)
      Fix deepspeed loading (part 2) (#37306)

Dan Saattrup Nielsen (1):
      fix: Add 'image-text-to-text' to `TASK_MAPPING` (#37107)

Dmitry Rogozhkin (1):
      tests: fix asyncio.wait() usage for python>=3.11 (#36898)

Ethan Knights (1):
      Update `trainer_pt_utils.py` docstrings for consistency (#36912)

Fanli Lin (2):
      [tests] remove cuda-only test marker in `AwqConfigTest`  (#37032)
      [tests] fix mamba integration simple inference precision issue (#37193)

Finn-Ole Höner (1):
      fixed typo (#37036)

Guang Yang (4):
      Export for Phi4-mini (#36780)
      Export T5 (encoder-decoder) to ExecuTorch (#36486)
      Use public export API on torch 2.5 and future (#36781)
      Fix static cache export (#37229)

Ilyas Moutawwakil (1):
      Only count num items in batch when needed (#36867)

Ita Zaporozhets (1):
      update error msg (#37207)

Jaime Fraustro (1):
      Add support for fast image processing in image-pretraining example (#37021)

Jerry Zhang (1):
      Add device workaround for int4 weight only quantization after API update (#36980)

Joao Gante (9):
      [Utils] torch version checks optionally accept dev versions (#36847)
      [generate, cache] handle more complex device maps (#37014)
      [generate] beam search -- fix output cropping (#37080)
      [Cache] rename dtype attribute 🚨 🚨  (#37044)
      [Tests] add `min_new_tokens` to prevent flaky length checks (#37175)
      [CI] lazy loading external datasets (#37218)
      [CI] green llama tests (#37244)
      [Tests] flaky `test_constrained_beam_search_generate_dict_output`  (#37276)
      [RoPE] abstract dynamic RoPE update under a decorator ✨  (#37249)

Josh Marshall (1):
      Fix removing "cpu" from frozenset in bitsandbytes.py to allow better ROCm support. (#36975)

Kyle Sayers (1):
      [Modeling] Load FP8 safetensors such as DeepSeek (#36828)

Linnet Cosmos Tuscano (1):
      Update OpenAI GPT model card (#37255)

Lysandre (1):
      Release: v4.51.0

Lysandre Debut (2):
      Hugging Face Hub pin to v0.30.0 for Xet (#37166)
      Hf Xet extra (#37305)

Manuel Faysse (1):
      Fix SDPA implementation in Qwen2-VL (issues with torch==2.6.0) (#36891)

Marc Sun (2):
      Fix cuda index issue in cache allocator (#36937)
      Log the correct learning rate (#36973)

Matt (7):
      No more dtype_byte_size() (#37144)
      Stop DOSing the Hub in the CI (#37209)
      More ReDOS fixes! (#36964)
      Fix AST parsing when looking for remote code imports (#37245)
      Allow flexible generation params arg when checking pipeline specs (#37211)
      Purge unused ModelTester code (#37085)
      Fix llava_onevision tests (#37280)

Michael Goin (1):
      Fix PixtralProcessor patch_size when spatial_merge_size is used (#37019)

MinJu-Ha (1):
      🌐 [i18n-KO] Translated `qwen2_vl.md` to Korean (#36750)

Minho Ryu (1):
      [WIP] add deepseek-v3 (#35926)

Mohamed Mekkouri (5):
      Fix Compressed tensors to_dict_diff (#36922)
      Disallow Offload to disk for gguf files (#36933)
      Fixing _pre_quantization_dtype when torch_dtype is None (#36930)
      Fix device_map check for ggml files (#37003)
      Skip FP8 linear tests For device capability < 9.0(#37008)

NargiT (1):
      typo fixed in README_fr.md (#36951)

Nikos Antoniou (1):
      Introduce modular files for speech models (#35902)

Parag Ekbote (1):
      Update Model Card for ModernBERT (#37052)

Parteek (1):
      Add Distill Any Depth (#36614)

Pavel Iakubovskii (4):
      Fix pytorch defomr attn path (#36923)
      Fixup for distill_any_depth conversion script (#37043)
      Refactor `return_dict` logic to remove complicated if/else paths (#36794)
      Refactor attention for SigLIP based models (#36981)

Perry Gibson (1):
      fix: Fully remove legacy cache from Llama (#36958)

Prem Kumar M (1):
      Replace default split function with jnp.split() in flax models (#37001)

Purusharth Malik (1):
      Updated the model card for CLIP (#37040)

Qizhi Chen (1):
      Convert `_VALID_DICT_FIELDS` to class attribute for shared dict parsing in subclasses (#36736)

Qubitium-ModelCloud (1):
      Fix 4090/ada not detected as having FP8 support (#37067)

Rahul Tuli (1):
      Fix: Unexpected Keys, Improve `run_compressed`, Rename Test Folder (#37077)

Raushan Turganbay (10):
      Fix torch version guard at import (#36907)
      [chameleon] fix num image token check (#36918)
      Deprecate #36741 and map Causal to Conditional (#36917)
      Support `return_tensors` in audio chat templates (#34601)
      [chat templates} support loading audio from video (#36955)
      [blip-2] Fix dtype mismatch when keep in fp32  (#37068)
      [qwen3] fix generation tests (#37142)
      [chat-template] fix video loading (#37146)
      [Phi4] add multimodal chat template (#36996)
      [qwen-vl] fix image processor (#37258)

Reshan Gomis (1):
      mobilebert model card update (#37256)

Ricardo Alanis (1):
      Update falcon model card (#37184)

Robin Kahlow (1):
      RWKV: fix mask warning typo (#37114)

Ryan McConville (1):
      Clarify error message to ensure min 28x28 image supplied for Qwen 2.5 VL (#37264)

Ryan Mullins (1):
      Adding links to ShieldGemma 2 technical report (#37247)

Sai-Suraj-27 (1):
      Updated docker files to use `uv` for installing packages (#36957)

Sharareh Younesian (1):
      Updated T5 model card with standardized format (#37261)

Shubham Panchal (1):
      Update model card for Depth Anything (#37065)

Steven Liu (3):
      [docs] Model docs (#36469)
      [docs] Fix image link (#36869)
      [docs] Attention mask image (#36970)

Sukriti Sharma (1):
      fix: loss computation after embeddings resize - mllama (#36840)

Sungyoon Jeong (1):
      Optimize `to_py_obj` for python-native numeric lists and scalars (#36885)

Surya Garikipati (1):
      Update model card for electra (#37063)

Thien Tran (1):
      Fix Gemma3 embedding scaling (#37109)

Tom Aarsen (1):
      [`ModernBERT`] Never save 'reference_compile' config; should be set based on end user (#36305)

Tugsbayasgalan Manlaibaatar (1):
      Make canine model exportable by removing unncessary complicated logic (#37124)

Xavier Dupré (1):
      Fixes DynamicCache export issues due to control flow and inplace modifications (#36652)

XinyuanTong (1):
      [Fix] Add `original_max_position_embeddings` to YARN rope_scaling optional keys (#36877)

Yao Matrix (5):
      fix transformers_cli import relative path issue (#36989)
      enable `test_assisted_decoding_in_different_gpu` test on XPU (#37120)
      fix XPU UT error case brough by RNG difference btw XPU and CUDA (#37121)
      enable 2 types of case on XPU (#37198)
      fix test device spec relative path importing issue (#37190)

Yaswanth Gali (1):
      Fix std initialization in Idefics variants (#37100)

Yih-Dar (18):
      Use another repo. for Mistral3 processor testing (#36925)
      More precise comment (#36935)
      Update ruff to `0.11.2` (#36962)
      Update after #36962 (#36965)
      update examples after ruff being updated (#36972)
      update bot comment again (#36974)
      byebye CircleCI TF jobs (#36998)
      Install `networkx==3.2.1` manually in some CircleCI jobs after #36957 (#37000)
      Mark 2 tests as flaky for now (#37038)
      Use `lru_cache` for tokenization tests (#36818)
      fix tied weigths issue  (#37031)
      Kenlm (#37091)
      skip (#37141)
      Avoid pipeline test failing related to Hub call (#37170)
      Skip code `307` in `RequestCounter` (#36953)
      Try to avoid/reduce some remaining CI job failures (#37202)
      Fix `utils/check_bad_commit.py` (#37272)
      pin specific `natten` version in docker file  (#37274)

Yoni Gozlan (3):
      Fix Pan and Scan on batched images Gemma3 (#36864)
      Fix processor kwargs qwen2 vl (#36890)
      🚨Deprecate legacy argument for image-text-to-text models and adopt new behavior by default (#36307)

Yuan Wu (1):
      Gaudi: Fix the pipeline failed issue with hpu device (#36990)

Yufeng Xu (1):
      Fixes the inconsistency of the optionality of attention_mask (#37153)

Zach Mueller (1):
      Update w/ new account (#37084)

Zhen (1):
      [Feature] Support using FlashAttention2 on Ascend NPU (#36696)

byi8220 (1):
      Disable delay_optimizer_creation in `Trainer` to support fsdp2 (#37147)

cyyever (19):
      [2/N] Use pyupgrade --py39-plus to improve code (#36857)
      Remove extra tensor clone in PyTorch code (#36748)
      Add ruff target-version (#36971)
      Fix tensor dtype mismatch (#36985)
      Use torch.expm1 (#36995)
      Fix Optional type annotation (#36841)
      Remove deprecated training arguments (#36946)
      Avoid unnecessary device operations in loss computing (#36950)
      Fix typing for None valued variables (#37004)
      Set weights_only in torch.load (#36991)
      Remove deprecated batch_size parameter (#37007)
      Change deprecated PT functions (#37041)
      Remove deprecated code (#37059)
      Fix more inefficient PT operations (#37060)
      Merge tensor operations with device transfer operations (#37097)
      [3/N] Use pyupgrade --py39-plus to improve code (#36936)
      Add py.typed (#37022)
      Add Optional to types (#37163)
      Fix deprecated PT functions (#37237)

efsotr (1):
      Support passing flash_attn_kwargs when gradient_checkpointing is enabled (#37037)

eustlb (1):
      [audio utils] fix fft_bin_width computation (#36603)

gautham (1):
      Added support for seed in `DataCollatorForWholeWordMask` (#36903)

hoshi-hiyouga (1):
      remove redundant code in trainer (#36994)

huismiling (1):
      [MLU] Fix FA2 check error, remove deepspeed-mlu deps. (#36159)

ivarflakstad (1):
      Fix get_device_properties (#36997)

jiqing-feng (5):
      fix pegasus init weights and other copied models (#36844)
      enable tp on CPU (#36299)
      fix whisper re-compile (#36712)
      add gpt2 test on XPU (#37028)
      Fix llava xpu tests. (#37130)

jp (1):
      fix: AttributeError: 'LlavaProcessor' object has no attribute 'image_token_id' (#37026)

omahs (1):
      Fix typos (#36910)

regisss (1):
      Add new dim to `num_items_in_batch` if necessary (#36967)

湛露先生 (5):
      Change GPUS to GPUs (#36945)
      clean pipeline question_answering. (#36986)
      Fix some typos about benchmark scripts. (#37027)
      fixed typo. (#37057)
      Fix some code annotation typos. (#37102)